// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/common/struct.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ObjectType } from "./enum_pb";
import { file_common_protobuf_common_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/common/struct.proto.
 */
export const file_common_protobuf_common_struct: GenFile = /*@__PURE__*/
  fileDesc("CiNjb21tb24vcHJvdG9idWYvY29tbW9uL3N0cnVjdC5wcm90bxIGY29tbW9uIjIKB1Bvc0luZm8SEQoJb2JqZWN0X2lkGAEgASgJEgkKAXgYAiABKAISCQoBeRgDIAEoAiJYCgpPYmplY3RJbmZvEiEKCHBvc19pbmZvGAEgASgLMg8uY29tbW9uLlBvc0luZm8SJwoLb2JqZWN0X3R5cGUYAiABKA4yEi5jb21tb24uT2JqZWN0VHlwZSIsCghVc2VySW5mbxIOCgZ1c2VySWQYASABKAkSEAoIdXNlck5hbWUYAiABKAliBnByb3RvMw", [file_common_protobuf_common_enum]);

/**
 * @generated from message common.PosInfo
 */
export type PosInfo = Message<"common.PosInfo"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;
};

/**
 * Describes the message common.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema: GenMessage<PosInfo> = /*@__PURE__*/
  messageDesc(file_common_protobuf_common_struct, 0);

/**
 * @generated from message common.ObjectInfo
 */
export type ObjectInfo = Message<"common.ObjectInfo"> & {
  /**
   * @generated from field: common.PosInfo pos_info = 1;
   */
  posInfo?: PosInfo;

  /**
   * OBJECT_TYPE_CREATURE, OBJECT_TYPE_PROJECTILE, OBJECT_TYPE_ENV;
   *
   * @generated from field: common.ObjectType object_type = 2;
   */
  objectType: ObjectType;
};

/**
 * Describes the message common.ObjectInfo.
 * Use `create(ObjectInfoSchema)` to create a new message.
 */
export const ObjectInfoSchema: GenMessage<ObjectInfo> = /*@__PURE__*/
  messageDesc(file_common_protobuf_common_struct, 1);

/**
 * @generated from message common.UserInfo
 */
export type UserInfo = Message<"common.UserInfo"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 유저 닉네임
   *
   * @generated from field: string userName = 2;
   */
  userName: string;
};

/**
 * Describes the message common.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema: GenMessage<UserInfo> = /*@__PURE__*/
  messageDesc(file_common_protobuf_common_struct, 2);

