// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/game/room.proto (package room, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { C2S_Metadata } from "../client/client_pb";
import { file_common_protobuf_client_client } from "../client/client_pb";
import type { S2C_Metadata } from "../server/server_pb";
import { file_common_protobuf_server_server } from "../server/server_pb";
import type { UserInfo } from "../common/struct_pb";
import { file_common_protobuf_common_struct } from "../common/struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/game/room.proto.
 */
export const file_common_protobuf_game_room: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb21tb24vcHJvdG9idWYvZ2FtZS9yb29tLnByb3RvEgRyb29tIkMKDUMyTF9FbnRlclJvb20SIgoEbWV0YRgBIAEoCzIULmNsaWVudC5DMlNfTWV0YWRhdGESDgoGcm9vbUlkGAIgASgEIm4KFEwyQ19FbnRlclJvb21OZXdVc2VyEiIKBG1ldGEYASABKAsyFC5zZXJ2ZXIuUzJDX01ldGFkYXRhEhEKCWlzRW50ZXJlZBgCIAEoCBIfCgV1c2VycxgDIAMoCzIQLmNvbW1vbi5Vc2VySW5mbyJfChZMMkNfRW50ZXJSb29tRXhpc3RVc2VyEiIKBG1ldGEYASABKAsyFC5zZXJ2ZXIuUzJDX01ldGFkYXRhEiEKB25ld1VzZXIYAiABKAsyEC5jb21tb24uVXNlckluZm9iBnByb3RvMw", [file_common_protobuf_client_client, file_common_protobuf_server_server, file_common_protobuf_common_struct]);

/**
 * 방 입장 요청 패킷
 *
 * @generated from message room.C2L_EnterRoom
 */
export type C2L_EnterRoom = Message<"room.C2L_EnterRoom"> & {
  /**
   * @generated from field: client.C2S_Metadata meta = 1;
   */
  meta?: C2S_Metadata;

  /**
   * 입장하려는 Room ID
   *
   * @generated from field: uint64 roomId = 2;
   */
  roomId: bigint;
};

/**
 * Describes the message room.C2L_EnterRoom.
 * Use `create(C2L_EnterRoomSchema)` to create a new message.
 */
export const C2L_EnterRoomSchema: GenMessage<C2L_EnterRoom> = /*@__PURE__*/
  messageDesc(file_common_protobuf_game_room, 0);

/**
 * 방 입장 응답 패킷(신규 유저)
 *
 * @generated from message room.L2C_EnterRoomNewUser
 */
export type L2C_EnterRoomNewUser = Message<"room.L2C_EnterRoomNewUser"> & {
  /**
   * 공통 응답 메타 데이터
   *
   * @generated from field: server.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 방 입장 성공 여부
   *
   * @generated from field: bool isEntered = 2;
   */
  isEntered: boolean;

  /**
   * 방에 있는 기존 유저 정보
   *
   * @generated from field: repeated common.UserInfo users = 3;
   */
  users: UserInfo[];
};

/**
 * Describes the message room.L2C_EnterRoomNewUser.
 * Use `create(L2C_EnterRoomNewUserSchema)` to create a new message.
 */
export const L2C_EnterRoomNewUserSchema: GenMessage<L2C_EnterRoomNewUser> = /*@__PURE__*/
  messageDesc(file_common_protobuf_game_room, 1);

/**
 * 방 입장 응답 패킷(기존 유저)
 *
 * @generated from message room.L2C_EnterRoomExistUser
 */
export type L2C_EnterRoomExistUser = Message<"room.L2C_EnterRoomExistUser"> & {
  /**
   * 공통 응답 메타 데이터
   *
   * @generated from field: server.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 신규 유저 정보
   *
   * @generated from field: common.UserInfo newUser = 2;
   */
  newUser?: UserInfo;
};

/**
 * Describes the message room.L2C_EnterRoomExistUser.
 * Use `create(L2C_EnterRoomExistUserSchema)` to create a new message.
 */
export const L2C_EnterRoomExistUserSchema: GenMessage<L2C_EnterRoomExistUser> = /*@__PURE__*/
  messageDesc(file_common_protobuf_game_room, 2);

