// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/client/client.proto (package client, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/client/client.proto.
 */
export const file_common_protobuf_client_client: GenFile = /*@__PURE__*/
  fileDesc("CiNjb21tb24vcHJvdG9idWYvY2xpZW50L2NsaWVudC5wcm90bxIGY2xpZW50IjUKDEMyU19NZXRhZGF0YRIOCgZ1c2VySWQYASABKAkSFQoNY2xpZW50VmVyc2lvbhgCIAEoCSJJChFDMkxfSW5pdGlhbFBhY2tldBIiCgRtZXRhGAEgASgLMhQuY2xpZW50LkMyU19NZXRhZGF0YRIQCghkZXZpY2VJZBgCIAEoCWIGcHJvdG8z");

/**
 * 공통 요청 메시지 구조
 *
 * @generated from message client.C2S_Metadata
 */
export type C2S_Metadata = Message<"client.C2S_Metadata"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 클라이언트 버전 (문자열)
   *
   * @generated from field: string clientVersion = 2;
   */
  clientVersion: string;
};

/**
 * Describes the message client.C2S_Metadata.
 * Use `create(C2S_MetadataSchema)` to create a new message.
 */
export const C2S_MetadataSchema: GenMessage<C2S_Metadata> = /*@__PURE__*/
  messageDesc(file_common_protobuf_client_client, 0);

/**
 * 최초 패킷 구조
 *
 * @generated from message client.C2L_InitialPacket
 */
export type C2L_InitialPacket = Message<"client.C2L_InitialPacket"> & {
  /**
   * @generated from field: client.C2S_Metadata meta = 1;
   */
  meta?: C2S_Metadata;

  /**
   * @generated from field: string deviceId = 2;
   */
  deviceId: string;
};

/**
 * Describes the message client.C2L_InitialPacket.
 * Use `create(C2L_InitialPacketSchema)` to create a new message.
 */
export const C2L_InitialPacketSchema: GenMessage<C2L_InitialPacket> = /*@__PURE__*/
  messageDesc(file_common_protobuf_client_client, 1);

