// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file request/common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file request/common.proto.
 */
export const file_request_common: GenFile = /*@__PURE__*/
  fileDesc("ChRyZXF1ZXN0L2NvbW1vbi5wcm90bxIGY29tbW9uImUKBlBhY2tldBIRCgloYW5kbGVySWQYASABKA0SDgoGdXNlcklkGAIgASgJEhUKDWNsaWVudFZlcnNpb24YAyABKAkSEAoIc2VxdWVuY2UYBCABKA0SDwoHcGF5bG9hZBgFIAEoDGIGcHJvdG8z");

/**
 * 공통 패킷 구조
 *
 * @generated from message common.Packet
 */
export type Packet = Message<"common.Packet"> & {
  /**
   * 핸들러 ID (4바이트)
   *
   * @generated from field: uint32 handlerId = 1;
   */
  handlerId: number;

  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 2;
   */
  userId: string;

  /**
   * 클라이언트 버전 (문자열)
   *
   * @generated from field: string clientVersion = 3;
   */
  clientVersion: string;

  /**
   * 유저의 호출 수 (42억)
   *
   * @generated from field: uint32 sequence = 4;
   */
  sequence: number;

  /**
   * 실제 데이터
   *
   * @generated from field: bytes payload = 5;
   */
  payload: Uint8Array;
};

/**
 * Describes the message common.Packet.
 * Use `create(PacketSchema)` to create a new message.
 */
export const PacketSchema: GenMessage<Packet> = /*@__PURE__*/
  messageDesc(file_request_common, 0);

