// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file request/common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file request/common.proto.
 */
export const file_request_common: GenFile = /*@__PURE__*/
  fileDesc("ChRyZXF1ZXN0L2NvbW1vbi5wcm90bxIGY29tbW9uIkMKCE1ldGFEYXRhEg4KBnVzZXJJZBgBIAEoCRIVCg1jbGllbnRWZXJzaW9uGAIgASgJEhAKCHNlcXVlbmNlGAMgASgNIj4KBkMyU1BvcxIeCgRtZXRhGAEgASgLMhAuY29tbW9uLk1ldGFEYXRhEgkKAXkYAiABKAUSCQoBeBgDIAEoBWIGcHJvdG8z");

/**
 * 공통 패킷 구조
 *
 * @generated from message common.MetaData
 */
export type MetaData = Message<"common.MetaData"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 클라이언트 버전 (문자열)
   *
   * @generated from field: string clientVersion = 2;
   */
  clientVersion: string;

  /**
   * 유저의 호출 수 (42억)
   *
   * @generated from field: uint32 sequence = 3;
   */
  sequence: number;
};

/**
 * Describes the message common.MetaData.
 * Use `create(MetaDataSchema)` to create a new message.
 */
export const MetaDataSchema: GenMessage<MetaData> = /*@__PURE__*/
  messageDesc(file_request_common, 0);

/**
 * @generated from message common.C2SPos
 */
export type C2SPos = Message<"common.C2SPos"> & {
  /**
   * 공통 메타 데이터(유저 ID, 버전, 호출 수)
   *
   * @generated from field: common.MetaData meta = 1;
   */
  meta?: MetaData;

  /**
   * y축 좌표
   *
   * @generated from field: int32 y = 2;
   */
  y: number;

  /**
   * x축 좌표
   *
   * @generated from field: int32 x = 3;
   */
  x: number;
};

/**
 * Describes the message common.C2SPos.
 * Use `create(C2SPosSchema)` to create a new message.
 */
export const C2SPosSchema: GenMessage<C2SPos> = /*@__PURE__*/
  messageDesc(file_request_common, 1);

