// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file request/initial.proto (package initial, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file request/initial.proto.
 */
export const file_request_initial: GenFile = /*@__PURE__*/
  fileDesc("ChVyZXF1ZXN0L2luaXRpYWwucHJvdG8SB2luaXRpYWwiIQoNSW5pdGlhbFBhY2tldBIQCghkZXZpY2VJZBgBIAEoCWIGcHJvdG8z");

/**
 * 최초 패킷 구조
 *
 * @generated from message initial.InitialPacket
 */
export type InitialPacket = Message<"initial.InitialPacket"> & {
  /**
   * @generated from field: string deviceId = 1;
   */
  deviceId: string;
};

/**
 * Describes the message initial.InitialPacket.
 * Use `create(InitialPacketSchema)` to create a new message.
 */
export const InitialPacketSchema: GenMessage<InitialPacket> = /*@__PURE__*/
  messageDesc(file_request_initial, 0);

