// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file enum.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file enum.proto.
 */
export const file_enum: GenFile = /*@__PURE__*/
  fileDesc("CgplbnVtLnByb3RvEghQcm90b2NvbCo1CgpPYmplY3RUeXBlEgoKBlBMQVlFUhAAEgsKB01PTlNURVIQARIOCgpQUk9KRUNUSUxFEAJiBnByb3RvMw");

/**
 * @generated from enum Protocol.ObjectType
 */
export enum ObjectType {
  /**
   * @generated from enum value: PLAYER = 0;
   */
  PLAYER = 0,

  /**
   * @generated from enum value: MONSTER = 1;
   */
  MONSTER = 1,

  /**
   * @generated from enum value: PROJECTILE = 2;
   */
  PROJECTILE = 2,
}

/**
 * Describes the enum Protocol.ObjectType.
 */
export const ObjectTypeSchema: GenEnum<ObjectType> = /*@__PURE__*/
  enumDesc(file_enum, 0);

