// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ObjectType } from "./enum_pb";
import { file_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file struct.proto.
 */
export const file_struct: GenFile = /*@__PURE__*/
  fileDesc("CgxzdHJ1Y3QucHJvdG8SCFByb3RvY29sIjEKB1Bvc0luZm8SEAoIb2JqZWN0SWQYASABKAkSCQoBeBgCIAEoAhIJCgF5GAMgASgCIloKCk9iamVjdEluZm8SIgoHcG9zSW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8SKAoKb2JqZWN0VHlwZRgCIAEoDjIULlByb3RvY29sLk9iamVjdFR5cGUiLAoIVXNlckluZm8SDgoGdXNlcklkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJIlQKCFJvb21JbmZvEg4KBnJvb21JZBgBIAEoDRIQCghyb29tTmFtZRgCIAEoCRIUCgxjdXJyZW50Q291bnQYAyABKAUSEAoIbWF4Q291bnQYBCABKAViBnByb3RvMw", [file_enum]);

/**
 * @generated from message Protocol.PosInfo
 */
export type PosInfo = Message<"Protocol.PosInfo"> & {
  /**
   * @generated from field: string objectId = 1;
   */
  objectId: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;
};

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema: GenMessage<PosInfo> = /*@__PURE__*/
  messageDesc(file_struct, 0);

/**
 * @generated from message Protocol.ObjectInfo
 */
export type ObjectInfo = Message<"Protocol.ObjectInfo"> & {
  /**
   * @generated from field: Protocol.PosInfo posInfo = 1;
   */
  posInfo?: PosInfo;

  /**
   * OBJECT_TYPE_CREATURE, OBJECT_TYPE_PROJECTILE, OBJECT_TYPE_ENV;
   *
   * @generated from field: Protocol.ObjectType objectType = 2;
   */
  objectType: ObjectType;
};

/**
 * Describes the message Protocol.ObjectInfo.
 * Use `create(ObjectInfoSchema)` to create a new message.
 */
export const ObjectInfoSchema: GenMessage<ObjectInfo> = /*@__PURE__*/
  messageDesc(file_struct, 1);

/**
 * @generated from message Protocol.UserInfo
 */
export type UserInfo = Message<"Protocol.UserInfo"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 유저 닉네임
   *
   * @generated from field: string nickname = 2;
   */
  nickname: string;
};

/**
 * Describes the message Protocol.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema: GenMessage<UserInfo> = /*@__PURE__*/
  messageDesc(file_struct, 2);

/**
 * @generated from message Protocol.RoomInfo
 */
export type RoomInfo = Message<"Protocol.RoomInfo"> & {
  /**
   * 방 ID
   *
   * @generated from field: uint32 roomId = 1;
   */
  roomId: number;

  /**
   * 방 이름
   *
   * @generated from field: string roomName = 2;
   */
  roomName: string;

  /**
   * 현재 인원 수
   *
   * @generated from field: int32 currentCount = 3;
   */
  currentCount: number;

  /**
   * 최대 인원 수
   *
   * @generated from field: int32 maxCount = 4;
   */
  maxCount: number;
};

/**
 * Describes the message Protocol.RoomInfo.
 * Use `create(RoomInfoSchema)` to create a new message.
 */
export const RoomInfoSchema: GenMessage<RoomInfo> = /*@__PURE__*/
  messageDesc(file_struct, 3);

