// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file game.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { C2S_Metadata } from "./client_pb";
import { file_client } from "./client_pb";
import type { S2C_Metadata } from "./server_pb";
import { file_server } from "./server_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file game.proto.
 */
export const file_game: GenFile = /*@__PURE__*/
  fileDesc("CgpnYW1lLnByb3RvEghQcm90b2NvbCJbChFDMkJfSW5pdGlhbFBhY2tldBIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuQzJTX01ldGFkYXRhEg4KBnJvb21JZBgCIAEoDRIQCghuaWNrbmFtZRgDIAEoCSI1Cg1CMkNfRW50ZXJSb29tEiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5TMkNfTWV0YWRhdGFiBnByb3RvMw", [file_client, file_server, file_struct]);

/**
 * @generated from message Protocol.C2B_InitialPacket
 */
export type C2B_InitialPacket = Message<"Protocol.C2B_InitialPacket"> & {
  /**
   * @generated from field: Protocol.C2S_Metadata meta = 1;
   */
  meta?: C2S_Metadata;

  /**
   * @generated from field: uint32 roomId = 2;
   */
  roomId: number;

  /**
   * @generated from field: string nickname = 3;
   */
  nickname: string;
};

/**
 * Describes the message Protocol.C2B_InitialPacket.
 * Use `create(C2B_InitialPacketSchema)` to create a new message.
 */
export const C2B_InitialPacketSchema: GenMessage<C2B_InitialPacket> = /*@__PURE__*/
  messageDesc(file_game, 0);

/**
 * @generated from message Protocol.B2C_EnterRoom
 */
export type B2C_EnterRoom = Message<"Protocol.B2C_EnterRoom"> & {
  /**
   * @generated from field: Protocol.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;
};

/**
 * Describes the message Protocol.B2C_EnterRoom.
 * Use `create(B2C_EnterRoomSchema)` to create a new message.
 */
export const B2C_EnterRoomSchema: GenMessage<B2C_EnterRoom> = /*@__PURE__*/
  messageDesc(file_game, 1);

