// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file room.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { C2S_Metadata } from "./client_pb";
import { file_client } from "./client_pb";
import type { S2C_Metadata } from "./server_pb";
import { file_server } from "./server_pb";
import type { UserInfo } from "./struct_pb";
import { file_struct } from "./struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file room.proto.
 */
export const file_room: GenFile = /*@__PURE__*/
  fileDesc("Cgpyb29tLnByb3RvEghQcm90b2NvbCJFCg1DMkxfRW50ZXJSb29tEiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5DMlNfTWV0YWRhdGESDgoGcm9vbUlkGAIgASgEInIKFEwyQ19FbnRlclJvb21OZXdVc2VyEiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5TMkNfTWV0YWRhdGESEQoJaXNFbnRlcmVkGAIgASgIEiEKBXVzZXJzGAMgAygLMhIuUHJvdG9jb2wuVXNlckluZm8iYwoWTDJDX0VudGVyUm9vbUV4aXN0VXNlchIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhEiMKB25ld1VzZXIYAiABKAsyEi5Qcm90b2NvbC5Vc2VySW5mb2IGcHJvdG8z", [file_client, file_server, file_struct]);

/**
 * 방 입장 요청 패킷
 *
 * @generated from message Protocol.C2L_EnterRoom
 */
export type C2L_EnterRoom = Message<"Protocol.C2L_EnterRoom"> & {
  /**
   * @generated from field: Protocol.C2S_Metadata meta = 1;
   */
  meta?: C2S_Metadata;

  /**
   * 입장하려는 Room ID
   *
   * @generated from field: uint64 roomId = 2;
   */
  roomId: bigint;
};

/**
 * Describes the message Protocol.C2L_EnterRoom.
 * Use `create(C2L_EnterRoomSchema)` to create a new message.
 */
export const C2L_EnterRoomSchema: GenMessage<C2L_EnterRoom> = /*@__PURE__*/
  messageDesc(file_room, 0);

/**
 * 방 입장 응답 패킷(신규 유저)
 *
 * @generated from message Protocol.L2C_EnterRoomNewUser
 */
export type L2C_EnterRoomNewUser = Message<"Protocol.L2C_EnterRoomNewUser"> & {
  /**
   * 공통 응답 메타 데이터
   *
   * @generated from field: Protocol.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 방 입장 성공 여부
   *
   * @generated from field: bool isEntered = 2;
   */
  isEntered: boolean;

  /**
   * 방에 있는 기존 유저 정보
   *
   * @generated from field: repeated Protocol.UserInfo users = 3;
   */
  users: UserInfo[];
};

/**
 * Describes the message Protocol.L2C_EnterRoomNewUser.
 * Use `create(L2C_EnterRoomNewUserSchema)` to create a new message.
 */
export const L2C_EnterRoomNewUserSchema: GenMessage<L2C_EnterRoomNewUser> = /*@__PURE__*/
  messageDesc(file_room, 1);

/**
 * 방 입장 응답 패킷(기존 유저)
 *
 * @generated from message Protocol.L2C_EnterRoomExistUser
 */
export type L2C_EnterRoomExistUser = Message<"Protocol.L2C_EnterRoomExistUser"> & {
  /**
   * 공통 응답 메타 데이터
   *
   * @generated from field: Protocol.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 신규 유저 정보
   *
   * @generated from field: Protocol.UserInfo newUser = 2;
   */
  newUser?: UserInfo;
};

/**
 * Describes the message Protocol.L2C_EnterRoomExistUser.
 * Use `create(L2C_EnterRoomExistUserSchema)` to create a new message.
 */
export const L2C_EnterRoomExistUserSchema: GenMessage<L2C_EnterRoomExistUser> = /*@__PURE__*/
  messageDesc(file_room, 2);

