// @generated by protoc-gen-es v2.2.1 with parameter "target=ts"
// @generated from file server.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file server.proto.
 */
export const file_server: GenFile = /*@__PURE__*/
  fileDesc("CgxzZXJ2ZXIucHJvdG8SCFByb3RvY29sIjcKDFMyQ19NZXRhZGF0YRIUCgxyZXNwb25zZUNvZGUYASABKA0SEQoJdGltZXN0YW1wGAIgASgDIkAKCEwyQ19Jbml0EiQKBG1ldGEYASABKAsyFi5Qcm90b2NvbC5TMkNfTWV0YWRhdGESDgoGdXNlcklkGAIgASgJIkIKCVMyQ19FcnJvchIkCgRtZXRhGAEgASgLMhYuUHJvdG9jb2wuUzJDX01ldGFkYXRhEg8KB21lc3NhZ2UYAiABKAkiJQoRQjJMX0luaXRpYWxQYWNrZXQSEAoIc2VydmVySWQYASABKAliBnByb3RvMw");

/**
 * 공통 응답 메시지 구조
 *
 * @generated from message Protocol.S2C_Metadata
 */
export type S2C_Metadata = Message<"Protocol.S2C_Metadata"> & {
  /**
   * 응답 코드 (성공: 0, 실패: 에러 코드)
   *
   * @generated from field: uint32 responseCode = 1;
   */
  responseCode: number;

  /**
   * 메시지 생성 타임스탬프 (Unix 타임스탬프)
   *
   * @generated from field: int64 timestamp = 2;
   */
  timestamp: bigint;
};

/**
 * Describes the message Protocol.S2C_Metadata.
 * Use `create(S2C_MetadataSchema)` to create a new message.
 */
export const S2C_MetadataSchema: GenMessage<S2C_Metadata> = /*@__PURE__*/
  messageDesc(file_server, 0);

/**
 * 유저 정보 응답 메시지
 *
 * @generated from message Protocol.L2C_Init
 */
export type L2C_Init = Message<"Protocol.L2C_Init"> & {
  /**
   * 공통 메타 데이터 (응답 코드, 타임스탬프, 시퀀스)
   *
   * @generated from field: Protocol.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 2;
   */
  userId: string;
};

/**
 * Describes the message Protocol.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema: GenMessage<L2C_Init> = /*@__PURE__*/
  messageDesc(file_server, 1);

/**
 * 에러 응답 메시지
 *
 * @generated from message Protocol.S2C_Error
 */
export type S2C_Error = Message<"Protocol.S2C_Error"> & {
  /**
   * 공통 메타 데이터 (응답 코드, 타임스탬프, 시퀀스)
   *
   * @generated from field: Protocol.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 에러 내용
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message Protocol.S2C_Error.
 * Use `create(S2C_ErrorSchema)` to create a new message.
 */
export const S2C_ErrorSchema: GenMessage<S2C_Error> = /*@__PURE__*/
  messageDesc(file_server, 2);

/**
 * 초기화 메시지
 *
 * @generated from message Protocol.B2L_InitialPacket
 */
export type B2L_InitialPacket = Message<"Protocol.B2L_InitialPacket"> & {
  /**
   * UUID
   *
   * @generated from field: string serverId = 1;
   */
  serverId: string;
};

/**
 * Describes the message Protocol.B2L_InitialPacket.
 * Use `create(B2L_InitialPacketSchema)` to create a new message.
 */
export const B2L_InitialPacketSchema: GenMessage<B2L_InitialPacket> = /*@__PURE__*/
  messageDesc(file_server, 3);

