// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ObjectType } from "./enum_pb";
import { file_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file struct.proto.
 */
export const file_struct: GenFile = /*@__PURE__*/
  fileDesc("CgxzdHJ1Y3QucHJvdG8SCFByb3RvY29sIjIKB1Bvc0luZm8SEQoJb2JqZWN0X2lkGAEgASgJEgkKAXgYAiABKAISCQoBeRgDIAEoAiJcCgpPYmplY3RJbmZvEiMKCHBvc19pbmZvGAEgASgLMhEuUHJvdG9jb2wuUG9zSW5mbxIpCgtvYmplY3RfdHlwZRgCIAEoDjIULlByb3RvY29sLk9iamVjdFR5cGUiLAoIVXNlckluZm8SDgoGdXNlcklkGAEgASgJEhAKCG5pY2tuYW1lGAIgASgJYgZwcm90bzM", [file_enum]);

/**
 * @generated from message Protocol.PosInfo
 */
export type PosInfo = Message<"Protocol.PosInfo"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;
};

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema: GenMessage<PosInfo> = /*@__PURE__*/
  messageDesc(file_struct, 0);

/**
 * @generated from message Protocol.ObjectInfo
 */
export type ObjectInfo = Message<"Protocol.ObjectInfo"> & {
  /**
   * @generated from field: Protocol.PosInfo pos_info = 1;
   */
  posInfo?: PosInfo;

  /**
   * OBJECT_TYPE_CREATURE, OBJECT_TYPE_PROJECTILE, OBJECT_TYPE_ENV;
   *
   * @generated from field: Protocol.ObjectType object_type = 2;
   */
  objectType: ObjectType;
};

/**
 * Describes the message Protocol.ObjectInfo.
 * Use `create(ObjectInfoSchema)` to create a new message.
 */
export const ObjectInfoSchema: GenMessage<ObjectInfo> = /*@__PURE__*/
  messageDesc(file_struct, 1);

/**
 * @generated from message Protocol.UserInfo
 */
export type UserInfo = Message<"Protocol.UserInfo"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 유저 닉네임
   *
   * @generated from field: string nickname = 2;
   */
  nickname: string;
};

/**
 * Describes the message Protocol.UserInfo.
 * Use `create(UserInfoSchema)` to create a new message.
 */
export const UserInfoSchema: GenMessage<UserInfo> = /*@__PURE__*/
  messageDesc(file_struct, 2);

