// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/response/contents.proto (package response, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { S2C_MetaData } from "./response_pb";
import { file_common_protobuf_response_response } from "./response_pb";
import { file_common_protobuf_enum } from "../enum_pb";
import type { ObjectInfo } from "../struct_pb";
import { file_common_protobuf_struct } from "../struct_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/response/contents.proto.
 */
export const file_common_protobuf_response_contents: GenFile = /*@__PURE__*/
  fileDesc("Cidjb21tb24vcHJvdG9idWYvcmVzcG9uc2UvY29udGVudHMucHJvdG8SCHJlc3BvbnNlIlwKDlMyQ19FTlRFUl9ST09NEiQKBG1ldGEYASABKAsyFi5yZXNwb25zZS5TMkNfTWV0YURhdGESJAoGcGxheWVyGAIgASgLMhQuUHJvdG9jb2wuT2JqZWN0SW5mb2IGcHJvdG8z", [file_common_protobuf_response_response, file_common_protobuf_enum, file_common_protobuf_struct]);

/**
 * 방 입장 응답 메시지
 *
 * @generated from message response.S2C_ENTER_ROOM
 */
export type S2C_ENTER_ROOM = Message<"response.S2C_ENTER_ROOM"> & {
  /**
   * 공통 메타 데이터 (응답 코드, 타임스탬프, 시퀀스)
   *
   * @generated from field: response.S2C_MetaData meta = 1;
   */
  meta?: S2C_MetaData;

  /**
   * Id, 위치, 타입
   *
   * @generated from field: Protocol.ObjectInfo player = 2;
   */
  player?: ObjectInfo;
};

/**
 * Describes the message response.S2C_ENTER_ROOM.
 * Use `create(S2C_ENTER_ROOMSchema)` to create a new message.
 */
export const S2C_ENTER_ROOMSchema: GenMessage<S2C_ENTER_ROOM> = /*@__PURE__*/
  messageDesc(file_common_protobuf_response_contents, 0);

