// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/enum.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/protobuf/enum.proto.
 */
export const file_common_protobuf_enum: GenFile = /*@__PURE__*/
  fileDesc("Chpjb21tb24vcHJvdG9idWYvZW51bS5wcm90bxIIUHJvdG9jb2wqVwoKT2JqZWN0VHlwZRIYChRPQkpFQ1RfVFlQRV9DUkVBVFVSRRAAEhoKFk9CSkVDVF9UWVBFX1BST0pFQ1RJTEUQARITCg9PQkpFQ1RfVFlQRV9FTlYQAmIGcHJvdG8z");

/**
 * @generated from enum Protocol.ObjectType
 */
export enum ObjectType {
  /**
   * @generated from enum value: OBJECT_TYPE_CREATURE = 0;
   */
  CREATURE = 0,

  /**
   * @generated from enum value: OBJECT_TYPE_PROJECTILE = 1;
   */
  PROJECTILE = 1,

  /**
   * @generated from enum value: OBJECT_TYPE_ENV = 2;
   */
  ENV = 2,
}

/**
 * Describes the enum Protocol.ObjectType.
 */
export const ObjectTypeSchema: GenEnum<ObjectType> = /*@__PURE__*/
  enumDesc(file_common_protobuf_enum, 0);

