// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/struct.proto (package Protocol, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ObjectType } from "./enum_pb";
import { file_common_protobuf_enum } from "./enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/struct.proto.
 */
export const file_common_protobuf_struct: GenFile = /*@__PURE__*/
  fileDesc("Chxjb21tb24vcHJvdG9idWYvc3RydWN0LnByb3RvEghQcm90b2NvbCIyCgdQb3NJbmZvEhEKCW9iamVjdF9pZBgBIAEoCRIJCgF4GAIgASgCEgkKAXkYAyABKAIiXAoKT2JqZWN0SW5mbxIjCghwb3NfaW5mbxgBIAEoCzIRLlByb3RvY29sLlBvc0luZm8SKQoLb2JqZWN0X3R5cGUYAiABKA4yFC5Qcm90b2NvbC5PYmplY3RUeXBlYgZwcm90bzM", [file_common_protobuf_enum]);

/**
 * @generated from message Protocol.PosInfo
 */
export type PosInfo = Message<"Protocol.PosInfo"> & {
  /**
   * @generated from field: string object_id = 1;
   */
  objectId: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;
};

/**
 * Describes the message Protocol.PosInfo.
 * Use `create(PosInfoSchema)` to create a new message.
 */
export const PosInfoSchema: GenMessage<PosInfo> = /*@__PURE__*/
  messageDesc(file_common_protobuf_struct, 0);

/**
 * @generated from message Protocol.ObjectInfo
 */
export type ObjectInfo = Message<"Protocol.ObjectInfo"> & {
  /**
   * @generated from field: Protocol.PosInfo pos_info = 1;
   */
  posInfo?: PosInfo;

  /**
   * OBJECT_TYPE_CREATURE, OBJECT_TYPE_PROJECTILE, OBJECT_TYPE_ENV;
   *
   * @generated from field: Protocol.ObjectType object_type = 2;
   */
  objectType: ObjectType;
};

/**
 * Describes the message Protocol.ObjectInfo.
 * Use `create(ObjectInfoSchema)` to create a new message.
 */
export const ObjectInfoSchema: GenMessage<ObjectInfo> = /*@__PURE__*/
  messageDesc(file_common_protobuf_struct, 1);

