// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/server/server.proto (package server, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/server/server.proto.
 */
export const file_common_protobuf_server_server: GenFile = /*@__PURE__*/
  fileDesc("CiNjb21tb24vcHJvdG9idWYvc2VydmVyL3NlcnZlci5wcm90bxIGc2VydmVyIjcKDFMyQ19NZXRhZGF0YRIUCgxyZXNwb25zZUNvZGUYASABKA0SEQoJdGltZXN0YW1wGAIgASgDIj4KCEwyQ19Jbml0EiIKBG1ldGEYASABKAsyFC5zZXJ2ZXIuUzJDX01ldGFkYXRhEg4KBnVzZXJJZBgCIAEoCSJACglTMkNfRXJyb3ISIgoEbWV0YRgBIAEoCzIULnNlcnZlci5TMkNfTWV0YWRhdGESDwoHbWVzc2FnZRgCIAEoCWIGcHJvdG8z");

/**
 * 공통 응답 메시지 구조
 *
 * @generated from message server.S2C_Metadata
 */
export type S2C_Metadata = Message<"server.S2C_Metadata"> & {
  /**
   * 응답 코드 (성공: 0, 실패: 에러 코드)
   *
   * @generated from field: uint32 responseCode = 1;
   */
  responseCode: number;

  /**
   * 메시지 생성 타임스탬프 (Unix 타임스탬프)
   *
   * @generated from field: int64 timestamp = 2;
   */
  timestamp: bigint;
};

/**
 * Describes the message server.S2C_Metadata.
 * Use `create(S2C_MetadataSchema)` to create a new message.
 */
export const S2C_MetadataSchema: GenMessage<S2C_Metadata> = /*@__PURE__*/
  messageDesc(file_common_protobuf_server_server, 0);

/**
 * 유저 정보 응답 메시지
 *
 * @generated from message server.L2C_Init
 */
export type L2C_Init = Message<"server.L2C_Init"> & {
  /**
   * 공통 메타 데이터 (응답 코드, 타임스탬프, 시퀀스)
   *
   * @generated from field: server.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 2;
   */
  userId: string;
};

/**
 * Describes the message server.L2C_Init.
 * Use `create(L2C_InitSchema)` to create a new message.
 */
export const L2C_InitSchema: GenMessage<L2C_Init> = /*@__PURE__*/
  messageDesc(file_common_protobuf_server_server, 1);

/**
 * 에러 응답 메시지
 *
 * @generated from message server.S2C_Error
 */
export type S2C_Error = Message<"server.S2C_Error"> & {
  /**
   * 공통 메타 데이터 (응답 코드, 타임스탬프, 시퀀스)
   *
   * @generated from field: server.S2C_Metadata meta = 1;
   */
  meta?: S2C_Metadata;

  /**
   * 에러 내용
   *
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * Describes the message server.S2C_Error.
 * Use `create(S2C_ErrorSchema)` to create a new message.
 */
export const S2C_ErrorSchema: GenMessage<S2C_Error> = /*@__PURE__*/
  messageDesc(file_common_protobuf_server_server, 2);

