// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file response/response.proto (package response, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file response/response.proto.
 */
export const file_response_response: GenFile = /*@__PURE__*/
  fileDesc("ChdyZXNwb25zZS9yZXNwb25zZS5wcm90bxIIcmVzcG9uc2UiZgoIUmVzcG9uc2USEQoJaGFuZGxlcklkGAEgASgNEhQKDHJlc3BvbnNlQ29kZRgCIAEoDRIRCgl0aW1lc3RhbXAYAyABKAMSDAoEZGF0YRgEIAEoDBIQCghzZXF1ZW5jZRgFIAEoDWIGcHJvdG8z");

/**
 * 공통 응답 메시지 구조
 *
 * @generated from message response.Response
 */
export type Response = Message<"response.Response"> & {
  /**
   * 핸들러 ID
   *
   * @generated from field: uint32 handlerId = 1;
   */
  handlerId: number;

  /**
   * 응답 코드 (성공: 0, 실패: 에러 코드)
   *
   * @generated from field: uint32 responseCode = 2;
   */
  responseCode: number;

  /**
   * 메시지 생성 타임스탬프 (Unix 타임스탬프)
   *
   * @generated from field: int64 timestamp = 3;
   */
  timestamp: bigint;

  /**
   * 실제 응답 데이터 (선택적 필드)
   *
   * @generated from field: bytes data = 4;
   */
  data: Uint8Array;

  /**
   * 시퀀스 값
   *
   * @generated from field: uint32 sequence = 5;
   */
  sequence: number;
};

/**
 * Describes the message response.Response.
 * Use `create(ResponseSchema)` to create a new message.
 */
export const ResponseSchema: GenMessage<Response> = /*@__PURE__*/
  messageDesc(file_response_response, 0);

