// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file common/protobuf/request/common.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/protobuf/request/common.proto.
 */
export const file_common_protobuf_request_common: GenFile = /*@__PURE__*/
  fileDesc("CiRjb21tb24vcHJvdG9idWYvcmVxdWVzdC9jb21tb24ucHJvdG8SBmNvbW1vbiI1CgxDMlNfTWV0YURhdGESDgoGdXNlcklkGAEgASgJEhUKDWNsaWVudFZlcnNpb24YAiABKAliBnByb3RvMw");

/**
 * 공통 요청 메시지 구조
 *
 * @generated from message common.C2S_MetaData
 */
export type C2S_MetaData = Message<"common.C2S_MetaData"> & {
  /**
   * 유저 ID (UUID, 16바이트)
   *
   * @generated from field: string userId = 1;
   */
  userId: string;

  /**
   * 클라이언트 버전 (문자열)
   *
   * @generated from field: string clientVersion = 2;
   */
  clientVersion: string;
};

/**
 * Describes the message common.C2S_MetaData.
 * Use `create(C2S_MetaDataSchema)` to create a new message.
 */
export const C2S_MetaDataSchema: GenMessage<C2S_MetaData> = /*@__PURE__*/
  messageDesc(file_common_protobuf_request_common, 0);

